/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parchisc5d419.vista;

import com.mycompany.parchisc5d419.controlador.ControladorPrincipal;

/**
 *
 * @author Usuario
 */
public class GUICredito extends javax.swing.JFrame {

    /**
     * Creates new form GUICredito
     */
    public GUICredito(ControladorPrincipal controlador) {
        initComponents();
        escuchar(controlador);
    }

    public void escuchar(ControladorPrincipal controlador) {
        btnAtras.addActionListener(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonAtras.png"))); // NOI18N
        btnAtras.setActionCommand("AtrasCreditos");
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 640, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Diseño grafico hecha por: Yuliana Masis");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Juego desarrollado por: Ethan Cabalceta Rojas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 740, 100));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tableroCreditos.png"))); // NOI18N
        getContentPane().add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlFondo;
    // End of variables declaration//GEN-END:variables
}
