/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parchisc5d419.vista;

import com.mycompany.parchisc5d419.controlador.ControladorPrincipal;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class GUIJugador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIJugador.class.getName());

    /**
     * Creates new form GUIJugador
     */
    public GUIJugador(ControladorPrincipal controlador) {
        initComponents();
        btnContinuar.addActionListener(controlador);
    }

    public String getCbColor() {
        return (String) cbColor.getSelectedItem();
    }

    public String getTxJugador1() {
        return txJugador1.getText();
    }

    public String getTxJugador2() {
        return txJugador2.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txJugador1 = new javax.swing.JTextField();
        txJugador2 = new javax.swing.JTextField();
        cbColor = new javax.swing.JComboBox<>();
        btnContinuar = new javax.swing.JButton();
        JLFondoPersonaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txJugador1.setColumns(20);
        getContentPane().add(txJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 230, 50));

        txJugador2.setColumns(20);
        getContentPane().add(txJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 250, 50));

        cbColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "Amarillo", "Rojo", "Azul", "Verde" }));
        getContentPane().add(cbColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 100, 40));

        btnContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonContinuar.png"))); // NOI18N
        btnContinuar.setActionCommand("Continuar");
        btnContinuar.setBorderPainted(false);
        btnContinuar.setContentAreaFilled(false);
        getContentPane().add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, -1, -1));

        JLFondoPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoPersonaje.png"))); // NOI18N
        getContentPane().add(JLFondoPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLFondoPersonaje;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JComboBox<String> cbColor;
    private javax.swing.JTextField txJugador1;
    private javax.swing.JTextField txJugador2;
    // End of variables declaration//GEN-END:variables
}
